<a href="https://colab.research.google.com/github/irinashipounova/Maths/blob/main/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82_%D0%BF%D0%BE_%D0%9C%D0%B0%D1%82%D1%81%D1%82%D0%B0%D1%82%D1%83.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Пусть y1 - уровень экспрессии гена ALPL, y2 - уровень экспрессии гена PTHR1, y3 - уровень экспрессии гена SPP1, y4 - уровень экспрессии гена BGLAP.

In [ ]:
y1 = np.array([0.173993611, 0.011689055, 0.057286478, 0.912670322, 1.087117967, 1.186394276, 0.130779223, 1.026961957, 0.183822469, 0.302185734, 0.38966726])
y2 = np.array([0.020182802, 0.0, 0.021167631, 0.078173729, 0.305906581, 0.016977479, 0.266638316, 0.006777721, 0.134330207, 0.038923388, 0.00654714])
y3 = np.array([0.132325031, 3.601489389, 1.689748358, 0.093969029, 0.121059051, 1.059695905, 0.441028372, 0.360569971, 0.766160486, 0.143179452, 0.391707761])
y4 = np.array([0.164215216, 1.219944603, 1.778394272, 0.715048416, 0.786543716, 0.734518373, 0.404642294, 0.82108052, 0.362878133, 0.212687896, 0.858664303])

In [ ]:
n1 = len(y1)
n2 = len(y2)
n3 = len(y3)
n4 = len(y4)
n = n1 + n2 + n3 + n4
n

44

In [ ]:
#всего групп 4
k = 4

Проведем однофакторный дисперсионный анализ. Сначала найдем средний уровень экспрессии гена в каждой группе:

In [ ]:
y1_mean = np.mean(y1)
y1_mean

0.4965971229090909

In [ ]:
y2_mean = np.mean(y2)
y2_mean

0.08142045400000002

In [ ]:
y3_mean = np.mean(y3)
y3_mean

0.8000848004545454

In [ ]:
y4_mean = np.mean(y4)
y4_mean

0.732601612909091

In [ ]:
y_all = np.concatenate([y1, y2, y3, y4])

In [ ]:
y_mean = np.mean(y_all)
y_mean

0.5276759975681817

In [ ]:
s2 = np.sum((y_all - y_mean)**2)
s2_f = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3 + ((y4_mean - y_mean)**2) * n4

In [ ]:
eta2 = s2_f / s2
eta2

0.18390425947592207

Не все группы статистически достоверно отличаются друг от друга.

Попарный т-тест с поправкой Бонферрони (количество попарных сравнений - 6, значит, пороговое значение p = 0.05/6 = 0,008).

In [ ]:
from scipy import stats 

In [ ]:
tval12, pval12 = stats.ttest_ind(y1, y2) 
print("t = " + str(tval12)) 
print("p = " + str(pval12)) 


t = 2.9286438277423255
p = 0.00830495012988769


**р равно 0.008, следовательно, экспрессия гена PTHR1 статистически достоверно НЕ отличается от экспрессии гена ALPL.**

In [ ]:
correlation_12 = np.corrcoef(y1, y2)
correlation_12

array([[1.        , 0.13014595],
       [0.13014595, 1.        ]])

**экспрессия гена PTHR1 статистически достоверно не коррелирует с экспрессией гена ALPL**

In [ ]:
tval13, pval13 = stats.ttest_ind(y1, y3) 
print("t = " + str(tval13)) 
print("p = " + str(pval13)) 


t = -0.8785625819345391
p = 0.3900717576941217


**р больше 0.008, следовательно, экспрессия гена SPP1 статистически достоверно НЕ отличается от экспрессии гена ALPL.**

In [ ]:
correlation_13 = np.corrcoef(y1, y3)
correlation_13

array([[ 1.        , -0.40988776],
       [-0.40988776,  1.        ]])

**экспрессия гена SPP1 статистически достоверно не коррелирует с экспрессией гена ALPL**

In [ ]:
tval14, pval14 = stats.ttest_ind(y1, y4) 
print("t = " + str(tval14)) 
print("p = " + str(pval14)) 


t = -1.1953651576981013
p = 0.24592636712583407


**р больше 0.008, следовательно, экспрессия гена BGLAP статистически достоверно НЕ отличается от экспрессии гена ALPL.**

In [ ]:
correlation_14 = np.corrcoef(y1, y4)
correlation_14

array([[ 1.        , -0.05429641],
       [-0.05429641,  1.        ]])

**экспрессия гена BGLAP статистически достоверно не коррелирует с экспрессией гена ALPL**

In [ ]:
tval23, pval23 = stats.ttest_ind(y2, y3) 
print("t = " + str(tval23)) 
print("p = " + str(pval23)) 


t = -2.257020387573023
p = 0.035350098860501666


**р больше 0.008, следовательно, экспрессия гена PTHR1 статистически достоверно НЕ отличается от экспрессии гена SPP1.**

In [ ]:
correlation_23 = np.corrcoef(y2, y3)
correlation_23

array([[ 1.        , -0.33618819],
       [-0.33618819,  1.        ]])

**экспрессия гена SPP1 статистически достоверно не коррелирует с экспрессией гена PTHR1**

In [ ]:
tval24, pval24 = stats.ttest_ind(y2, y4) 
print("t = " + str(tval24)) 
print("p = " + str(pval24)) 


t = -4.489294372771562
p = 0.000224296670724338


**р меньше 0.008, следовательно, экспрессия гена PTHR1 статистически достоверно отличается от экспрессии гена BGLAP.**

In [ ]:
correlation_24 = np.corrcoef(y2, y4)
correlation_24

array([[ 1.      , -0.254876],
       [-0.254876,  1.      ]])

**экспрессия гена BGLAP статистически достоверно не коррелирует с экспрессией гена PTHR1**

In [ ]:
tval34, pval34 = stats.ttest_ind(y3, y4) 
print("t = " + str(tval34)) 
print("p = " + str(pval34)) 


t = 0.19458882760490112
p = 0.8476778742032526


**р больше 0.008, следовательно, экспрессия гена BGLAP статистически достоверно НЕ отличается от экспрессии гена SPP1.**

In [ ]:
correlation_34 = np.corrcoef(y3, y4)
correlation_34

array([[1.        , 0.61617655],
       [0.61617655, 1.        ]])

**экспрессия гена BGLAP статистически достоверно коррелирует с экспрессией гена SPP1**

# **Итог: статистически достоверно различаются уровни экспрессии генов PTHR1 и BGLAP. Экспрессия гена BGLAP положительно коррелирует с экспрессией гена SPP1.**